### ISSUE TITLE
model.epochs in SGNS_VI

### ISSUE THREAD

**Issue by vaibhav29498** [Garrafao/LSCDetection#2]
The [official Gensim documentation](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.train) says "In the common and recommended case where train() is only called once, you can set _epochs=self.iter_." (iter attribute has been deprecated and replaced by epochs) However, in the vector initialization alignment method, the train function is called twice. Therefore do we need to explicitly pass the number of epochs while calling train() for the second time?

**Comment by Garrafao** [comment]
Are you referring to the latest SGNS_VI version? (It has been updated recently.) Because in the current version it is passed explicitly, as far as I can see:

`model.train(sentences, total_examples=model.corpus_count, epochs=model.epochs)`

**Comment by vaibhav29498** [comment]
I was talking about the latest version only. I thought that the Gensim documentation is recommending against the use of `model.epochs` when train function is being called multiple times because the epochs parameter is being updated by it. However, I just checked and it is not the case.

I guess that the recommendation is just to prevent confusion about the **total** number of epochs. Anyway, that should not be the case here.
